Import('*')

SRC=simpleglob("*.cc")

srcenv.Append(CPPPATH=['#/src/editor'])

# Ordering is important in the following calls!
libs=[]
libs+=SConscript('tools/SConscript')
libs+=SConscript('ui_menus/SConscript')
libs+=srcenv.StaticLibrary(target='editor', source=SRC)

Return('libs')

