Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/illegal_character_after_closing_brace/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_after_closing_brace/allowed')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_after_closing_brace/documentation')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_after_closing_brace/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_after_closing_brace/redundant_with_whitespace_checker')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_after_closing_brace/regexps')

