Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/loop_with_numerical_constant_condition/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/loop_with_numerical_constant_condition/allowed')
distadd(env, 'utils/spurious_source_code/regexps/loop_with_numerical_constant_condition/documentation')
distadd(env, 'utils/spurious_source_code/regexps/loop_with_numerical_constant_condition/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/loop_with_numerical_constant_condition/regexps')
