#!/usr/bin/python

# CamelCase names for class, struct, enum, using

error_msg="Use CapitalLetterWithCamelCase when naming an enum class, struct, or \"using\"."

regexp=r"""(^\s*((class|struct)\s+((\S+_)|([a-z]\S+)).*{)|((enum)\s+((\S+_)|(([abd-z])|(c(?!lass))\S+)).*{)|((using)\s+((\S+_)|([a-z]\S+)).*=).*$)"""

forbidden = [
    "class my_class",
    "class myClass",
    "struct my_struct",
    "struct myStruct",
    "using my_typedef",
    "using myTypedef",
    "enum class my_enum",
    "enum class myEnum"
    "enum my_enum",
    "enum myEnum"
]

allowed = [
    "class MyClass",
    "struct MyStruct",
    "using MyTypedef",
    "enum class MyEnum",
    "enum MyEnum"
]
