#!/usr/bin/python

# CamelCase names for class, struct, enum, using

error_msg="Use CamelCase when naming a class, struct, using, or enum."

regexp=r"""(^\s*((class|struct|enum)\s*\S+_.*{)|((using)\s*\S+_.*=).*$)"""

forbidden = [
    "class my_class",
    "struct my_struct",
    "using my_typedef",
    "enum my_enum"
]

allowed = [
    "class MyClass",
    "struct MyStruct",
    "using MyTypedef",
    "enum MyEnum"
]
