#!/usr/bin/python


error_msg = "Do not use operator synonyms, e.g. use \"&&\" rather than \"and\"."

# NOCOM(#GunChleoc) this rule does not exclude string literals, e.g. _(" or ")
# NOCOM(#GunChleoc) this rule does not exclude RST comments or // inline comments added after code
# NOCOM(#GunChleoc) this rule is always triggered twice
regexp = (
		r"""("""
		r"""^(?!((\s*[*])|(\s*/))).+\Wand(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wbitand(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wor(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wxor(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wnot(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wcompl(\W|$)"""
		r""")"""
	)

forbidden = [
    "and",
    "bitand",
    "and_eq",
    "or",
    "or_eq",
    "xor",
    "xor_eq",
    "not",
    "not_eq",
    "compl"
]

allowed = [
    "&&",
    "&",
    "&=",
    "||",
    "|=",
    "^",
    "^=",
    "!",
    "!=",
    "~"
]

