#!/usr/bin/python


error_msg = "Do not use operator synonyms, e.g. use \"&&\" rather than \"and\"."

# this rule does not protect string literals, e.g. _(" or ") or // inline comments added after code
regexp = (
		r"""("""
		r"""^(?!((\s*[*])|(\s*/))).+[\s\W]and([\s\W]|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+[\s\W]bitand([\s\W]|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+[\s\W]or([\s\W]|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+[\s\W]xor([\s\W]|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+[\s\W]not([\s\W]|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+[\s\W]compl([\s\W]|$)"""
		r""")"""
	)

forbidden = [
    "and",
    "bitand",
    "and_eq",
    "or",
    "or_eq",
    "xor",
    "xor_eq",
    "not",
    "not_eq",
    "compl"
]

allowed = [
    "&&",
    "&",
    "&=",
    "||",
    "|=",
    "^",
    "^=",
    "!",
    "!=",
    "~"
]

