#!/usr/bin/python

"""
Prefer DEBUG.
"""

error_msg="Do not use SDL integer data types (Uint8, Sint32 etc.). Instead use C++11 stdint.h types (uint8_t, int32_t etc.)."

regexp=r"""(^Uint[0-9]|Sint[0-9])"""

forbidden = [
    "Uint8",
    "Sint32"
]

allowed = [
    "uint8_t",
    "int32_t"
]
