#!/usr/bin/python


error_msg = "Do not use operator synonyms, e.g. use \"&&\" rather than \"and\"."

# this rule does not protect string literals, e.g. _(" or ") or // inline comments added after code
regexp = (
		r"""("""
		r"""^(?!((\s*[*])|(\s*/))).+\Wand(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wbitand(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wor(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wxor(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wnot(\W|$)"""
		r"""|^(?!((\s*[*])|(\s*/))).+\Wcompl(\W|$)"""
		r""")"""
	)

forbidden = [
    "and",
    "bitand",
    "and_eq",
    "or",
    "or_eq",
    "xor",
    "xor_eq",
    "not",
    "not_eq",
    "compl"
]

allowed = [
    "&&",
    "&",
    "&=",
    "||",
    "|=",
    "^",
    "^=",
    "!",
    "!=",
    "~"
]

