#!/usr/bin/python


"""
This catches a space before a closing grouping token (bracket, brace or
parenthesis), semicolon or comma. Characters inside "" and after // are
ignored.
"""

error_msg = "No space before ), }, ; allowed!"

regexp = r"""^([^/#"']|/([^/"']|"([^"]|\\")*"|'(\\[\'0nt]|[^\'])')|"([^"\]|\\"|\\[^"])*"|'(\\[\'0nt]|[^\'])')*/? []);,]"""

forbidden = [
    ' )',
    '	/ )',
    '; ;',
]

allowed = [
    '// }',
    '// )',
    '	// )',
    '" )"',
    '" \")"',
    '	 " \")"',
]
