#!/usr/bin/python


"""
This catches an opening parenthesis followed by a space or end of line.
"""

error_msg="No space or newline allowed after opening parenthesis."

strip_comments_and_strings = True
regexp=r"""\(( |$|\n)"""

forbidden = [
    '( h',
    '( ',
    '(',
    '/(',
    '/ /(',
    '/ / (',
    '/ / /(',
    '/ / /(\nadjh',

    # Eriks tests
    ## illegal_character_after_opening_parenthesis.cc
    'void f( float) {',
]

allowed = [
    '(h',
    '//(',
    '// (',
    '// (',
    '/* Convert \n * string blah ( \n */',
]
