#!/usr/bin/env python -tt
# encoding: utf-8
#

"""
Indentation should be done with tabs, but spaces are allowed for alignment.

This is not obligatory for macros, because of the Alignement of the \\ at the end
"""

import re

error_msg="Use tabs for indentation."

strip_comments_and_strings = True
strip_macros = True

class EvalMatches( object ):
    STARTS_WITH_SPACES = re.compile(r"^ +")
    def __call__(self, lines, fn):
        errors = []
        for curline, l in enumerate(lines, 1):
            if self.STARTS_WITH_SPACES.match(l):
                if l.rstrip().endswith(",") or l.rstrip().endswith("{"):
                    continue
                errors.append( (fn, curline, error_msg))
        return errors


evaluate_matches = EvalMatches()

forbidden = [
    "   if(a)\n",
]

allowed = [
    "if\n",
    "\tif(a) {\n",
    "  // Comment is ok",
    "/*\n * Multiline comment too */",
    "#in macros\\\nHi\\\n Hi", # \\\n   it's ok too",
]
