Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/misused_tab/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/misused_tab/allowed')
distadd(env, 'utils/spurious_source_code/regexps/misused_tab/documentation')
distadd(env, 'utils/spurious_source_code/regexps/misused_tab/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/misused_tab/redundant_with_whitespace_checker')
distadd(env, 'utils/spurious_source_code/regexps/misused_tab/regexps')

