Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/illegal_space_after_opening_parenthesis/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/illegal_space_after_opening_parenthesis/allowed')
distadd(env, 'utils/spurious_source_code/regexps/illegal_space_after_opening_parenthesis/documentation')
distadd(env, 'utils/spurious_source_code/regexps/illegal_space_after_opening_parenthesis/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/illegal_space_after_opening_parenthesis/redundant_with_whitespace_checker')
distadd(env, 'utils/spurious_source_code/regexps/illegal_space_after_opening_parenthesis/regexps')

