import os
import numpy

env = Environment(CXX="clang++")
env.Append(CCFLAGS= "-Wall -g")

## The main library
env.ParseConfig("pkg-config sdl --cflags")
env.ParseConfig("pkg-config sdl --libs")
env.Append(LIBS="SDL_ttf")
env.Append(CPPPATH="../../src/graphic/text")
env.Append(CPPPATH="../../src/")
rt_srcs = Glob("../../src/graphic/text/*.cc")
rt_lib = env.Library(rt_srcs)

# Debug program that renders one text
render_env = env.Clone()
render_env.Append(LIBS=[rt_lib])
render_env.Program("render", ["render.cc", "lodepng.cc", "thin_graphic.cc"])

# Python library
pylib_env = env.Environment(PYEXT_USE_DISTUTILS=True, SHCXX="clang++", ENV = {'PATH': os.environ["PATH"]})
pylib_env.Tool("pyext")
pylib_env.Tool("cython")
pylib_env.ParseConfig("pkg-config sdl --cflags")
pylib_env.ParseConfig("pkg-config sdl --libs")
pylib_env.Append(CPPPATH="../../src/graphic/text")
pylib_env.Append(CPPPATH="../../src/")
pylib_env.Append(LIBS=["SDL_ttf", rt_lib])
pylib_env.Append(CPPPATH=numpy.get_include())
ext = pylib_env.PythonExtension("pyrt_render",
    ["pyrt_render.pyx", "thin_graphic.cc", "lodepng.cc"],
)
