-- =======================================================================
--                                 Player 1
-- =======================================================================
p1:allow_buildings("all")
p1:forbid_buildings({"frisians_quarry", "frisians_hunters_house", "frisians_tavern", "frisians_coalmine", "frisians_ironmine", "frisians_goldmine", "frisians_rockmine"})

for i,f in ipairs({
   map:get_field(90, 114),
   map:get_field(90, 119),
   map:get_field(89, 168),
   map:get_field(87, 161),
   map:get_field(95, 181),
   map:get_field(97, 174),
   map:get_field(95, 198),
   map:get_field(90, 204),
}) do
   p1:place_ship(f)
end

-- Mostly autogenerated file with a bunch of manual edits.
-- Thanks for hessenfarmer for the script which I used (with some modifications) to generate this file.

local eco = {
  buildings=     {
      [1] =         {
          workers=             {
              frisians_seamstress= 1,
              frisians_farmer= 1,
              frisians_smelter= 3,
              frisians_forester= 2,
              frisians_hunter= 0,
              frisians_builder= 8,
              frisians_fisher= 0,
              frisians_reed_farmer= 0,
              frisians_trainer= 2,
              frisians_stonemason= 2,
              frisians_woodcutter= 2,
              frisians_reindeer_breeder= 1,
              frisians_claydigger= 3,
              frisians_blacksmith_master= 0,
              frisians_fruit_collector= 2,
              frisians_landlady= 0,
              frisians_brewer_master= 0,
              frisians_baker_master= 0,
              frisians_scout= 0,
              frisians_blacksmith= 0,
              frisians_carrier= 100,
              frisians_reindeer= 5,
              frisians_shipwright= 0,
              frisians_charcoal_burner= 1,
              frisians_miner= 0,
              frisians_miner_master= 0,
              frisians_geologist= 0,
              frisians_brewer= 1,
              frisians_brickmaker= 2,
              frisians_baker= 0,
              frisians_smoker= 2,
              frisians_seamstress_master= 0,
              frisians_beekeeper= 2,
              frisians_berry_farmer= 2,
            },
          name= "frisians_headquarters",
          wares=             {
              granite= 32,
              brick= 44,
              mead= 0,
              meal= 0,
              helmet= 0,
              bread_frisians= 33,
              fire_tongs= 2,
              iron_ore= 10,
              gold= 1,
              log= 49,
              coal= 20,
              iron= 16,
              fur_garment_studded= 0,
              reed= 48,
              gold_ore= 4,
              sword_short= 0,
              fur_garment_golden= 0,
              shovel= 2,
              helmet_golden= 0,
              felling_ax= 1,
              fur= 0,
              fish= 177,
              sword_broad= 0,
              sword_long= 0,
              scrap_iron= 0,
              needles= 2,
              basket= 0,
              beer= 28,
              clay= 4,
              ration= 0,
              bread_paddle= 1,
              pick= 1,
              honey_bread= 0,
              meat= 0,
              fishing_net= 3,
              hammer= 1,
              sword_double= 0,
              honey= 0,
              fur_garment= 3,
              smoked_meat= 2,
              scythe= 1,
              water= 63,
              barley= 5,
              fruit= 0,
              fur_garment_old= 0,
              scrap_metal_mixed= 0,
              cloth= 0,
              smoked_fish= 12,
              kitchen_tools= 1,
            },
          soldiers=             {
            },
          x= 89,
          y= 140,
          inputs=             {
            },
        },
      [2] =         {
          workers=             {
              frisians_carrier= 1,
            },
          name= "frisians_well",
          wares=             {
            },
          soldiers=             {
            },
          x= 90,
          y= 138,
          inputs=             {
            },
        },
      [3] =         {
          workers=             {
              frisians_reindeer_breeder= 1,
            },
          name= "frisians_reindeer_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 86,
          y= 143,
          inputs=             {
              water= 0,
              barley= 8,
            },
        },
      [4] =         {
          workers=             {
              frisians_carrier= 1,
            },
          name= "frisians_well",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 140,
          inputs=             {
            },
        },
      [5] =         {
          workers=             {
            },
          name= "frisians_outpost",
          wares=             {
            },
          soldiers=             {
              ["0000"]= 6,
            },
          x= 88,
          y= 144,
          inputs=             {
            },
        },
      [6] =         {
          workers=             {
              frisians_baker= 1,
            },
          name= "frisians_bakery",
          wares=             {
            },
          soldiers=             {
            },
          x= 85,
          y= 139,
          inputs=             {
              water= 1,
              barley= 7,
            },
        },
      [7] =         {
          workers=             {
              frisians_brewer= 1,
            },
          name= "frisians_brewery",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 138,
          inputs=             {
              water= 1,
              barley= 7,
            },
        },
      [8] =         {
          workers=             {
              frisians_baker= 1,
            },
          name= "frisians_bakery",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 136,
          inputs=             {
              water= 4,
              barley= 7,
            },
        },
      [9] =         {
          workers=             {
              frisians_brickmaker= 1,
            },
          name= "frisians_brick_kiln",
          wares=             {
            },
          soldiers=             {
            },
          x= 89,
          y= 136,
          inputs=             {
              granite= 3,
              clay= 6,
              coal= 2,
            },
        },
      [10] =         {
          workers=             {
              frisians_smoker= 1,
            },
          name= "frisians_smokery",
          wares=             {
            },
          soldiers=             {
            },
          x= 88,
          y= 134,
          inputs=             {
              log= 6,
              meat= 1,
              fish= 6,
            },
        },
      [11] =         {
          workers=             {
              frisians_carrier= 1,
            },
          name= "frisians_well",
          wares=             {
            },
          soldiers=             {
            },
          x= 84,
          y= 141,
          inputs=             {
            },
        },
      [12] =         {
          workers=             {
              frisians_smelter= 1,
            },
          name= "frisians_recycling_center",
          wares=             {
            },
          soldiers=             {
            },
          x= 86,
          y= 134,
          inputs=             {
              scrap_metal_mixed= 0,
              fur_garment_old= 0,
              scrap_iron= 0,
              coal= 3,
            },
        },
      [13] =         {
          workers=             {
              frisians_smelter= 1,
            },
          name= "frisians_furnace",
          wares=             {
            },
          soldiers=             {
            },
          x= 86,
          y= 132,
          inputs=             {
              gold_ore= 8,
              iron_ore= 8,
              coal= 0,
            },
        },
      [14] =         {
          workers=             {
              frisians_charcoal_burner= 1,
            },
          name= "frisians_charcoal_kiln",
          wares=             {
            },
          soldiers=             {
            },
          x= 86,
          y= 130,
          inputs=             {
              clay= 0,
              log= 8,
            },
        },
      [15] =         {
          workers=             {
            },
          name= "frisians_fortress",
          wares=             {
            },
          soldiers=             {
              ["0000"]= 12,
            },
          x= 87,
          y= 128,
          inputs=             {
            },
        },
      [16] =         {
          workers=             {
            },
          name= "frisians_port",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 119,
          inputs=             {
            },
        },
      [17] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 92,
          y= 124,
          inputs=             {
            },
        },
      [18] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 92,
          y= 122,
          inputs=             {
            },
        },
      [19] =         {
          workers=             {
              frisians_baker= 1,
            },
          name= "frisians_bakery",
          wares=             {
            },
          soldiers=             {
            },
          x= 90,
          y= 131,
          inputs=             {
              water= 7,
              barley= 7,
            },
        },
      [20] =         {
          workers=             {
              frisians_blacksmith= 1,
            },
          name= "frisians_blacksmithy",
          wares=             {
            },
          soldiers=             {
            },
          x= 89,
          y= 129,
          inputs=             {
              iron= 7,
              log= 7,
              reed= 4,
            },
        },
      [21] =         {
          workers=             {
              frisians_brewer= 1,
            },
          name= "frisians_brewery",
          wares=             {
            },
          soldiers=             {
            },
          x= 91,
          y= 129,
          inputs=             {
              water= 0,
              barley= 7,
            },
        },
      [22] =         {
          workers=             {
              frisians_blacksmith= 1,
            },
          name= "frisians_armor_smithy_small",
          wares=             {
            },
          soldiers=             {
            },
          x= 90,
          y= 127,
          inputs=             {
              iron= 8,
              coal= 0,
            },
        },
      [23] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 92,
          y= 126,
          inputs=             {
            },
        },
      [24] =         {
          workers=             {
              frisians_charcoal_burner= 1,
            },
          name= "frisians_charcoal_kiln",
          wares=             {
            },
          soldiers=             {
            },
          x= 90,
          y= 125,
          inputs=             {
              clay= 0,
              log= 8,
            },
        },
      [25] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 93,
          y= 128,
          inputs=             {
            },
        },
      [26] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 93,
          y= 130,
          inputs=             {
            },
        },
      [27] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 94,
          y= 132,
          inputs=             {
            },
        },
      [28] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 94,
          y= 134,
          inputs=             {
            },
        },
      [29] =         {
          workers=             {
              frisians_smelter= 1,
            },
          name= "frisians_recycling_center",
          wares=             {
            },
          soldiers=             {
            },
          x= 92,
          y= 134,
          inputs=             {
              scrap_metal_mixed= 0,
              fur_garment_old= 0,
              scrap_iron= 0,
              coal= 8,
            },
        },
      [30] =         {
          workers=             {
              frisians_smelter= 1,
            },
          name= "frisians_furnace",
          wares=             {
            },
          soldiers=             {
            },
          x= 92,
          y= 132,
          inputs=             {
              gold_ore= 8,
              iron_ore= 8,
              coal= 0,
            },
        },
      [31] =         {
          workers=             {
              frisians_seamstress= 1,
            },
          name= "frisians_sewing_room",
          wares=             {
            },
          soldiers=             {
            },
          x= 93,
          y= 136,
          inputs=             {
              fur= 0,
            },
        },
      [32] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 92,
          y= 140,
          inputs=             {
            },
        },
      [33] =         {
          workers=             {
              frisians_smoker= 1,
            },
          name= "frisians_smokery",
          wares=             {
            },
          soldiers=             {
            },
          x= 92,
          y= 138,
          inputs=             {
              log= 6,
              meat= 0,
              fish= 6,
            },
        },
      [34] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 91,
          y= 142,
          inputs=             {
            },
        },
      [35] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 90,
          y= 144,
          inputs=             {
            },
        },
      [36] =         {
          workers=             {
              frisians_claydigger= 1,
            },
          name= "frisians_clay_pit",
          wares=             {
            },
          soldiers=             {
            },
          x= 94,
          y= 139,
          inputs=             {
              water= 0,
            },
        },
      [37] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 89,
          y= 146,
          inputs=             {
            },
        },
      [38] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 88,
          y= 148,
          inputs=             {
            },
        },
      [39] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 150,
          inputs=             {
            },
        },
      [40] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 86,
          y= 152,
          inputs=             {
            },
        },
      [41] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 81,
          y= 155,
          inputs=             {
            },
        },
      [42] =         {
          workers=             {
              frisians_blacksmith= 1,
            },
          name= "frisians_blacksmithy",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 146,
          inputs=             {
              iron= 7,
              log= 7,
              reed= 4,
            },
        },
      [43] =         {
          workers=             {
            },
          name= "frisians_fortress",
          wares=             {
            },
          soldiers=             {
              ["0000"]= 12,
            },
          x= 79,
          y= 161,
          inputs=             {
            },
        },
      [44] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 75,
          y= 164,
          inputs=             {
            },
        },
      [45] =         {
          workers=             {
            },
          name= "frisians_port",
          wares=             {
            },
          soldiers=             {
            },
          x= 86,
          y= 166,
          inputs=             {
            },
        },
      [46] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 76,
          y= 160,
          inputs=             {
            },
        },
      [47] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 77,
          y= 155,
          inputs=             {
            },
        },
      [48] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 73,
          y= 155,
          inputs=             {
            },
        },
      [49] =         {
          workers=             {
              frisians_brickmaker= 1,
            },
          name= "frisians_brick_kiln",
          wares=             {
            },
          soldiers=             {
            },
          x= 85,
          y= 150,
          inputs=             {
              granite= 3,
              clay= 6,
              coal= 3,
            },
        },
      [50] =         {
          workers=             {
            },
          name= "frisians_fortress",
          wares=             {
            },
          soldiers=             {
              ["0000"]= 12,
            },
          x= 86,
          y= 174,
          inputs=             {
            },
        },
      [51] =         {
          workers=             {
              frisians_seamstress= 1,
            },
          name= "frisians_weaving_mill",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 176,
          inputs=             {
              fur= 3,
              reed= 6,
            },
        },
      [52] =         {
          workers=             {
              frisians_reed_farmer= 1,
            },
          name= "frisians_reed_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 91,
          y= 171,
          inputs=             {
            },
        },
      [53] =         {
          workers=             {
              frisians_reed_farmer= 1,
            },
          name= "frisians_reed_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 94,
          y= 171,
          inputs=             {
            },
        },
      [54] =         {
          workers=             {
              frisians_reed_farmer= 1,
            },
          name= "frisians_reed_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 93,
          y= 168,
          inputs=             {
            },
        },
      [55] =         {
          workers=             {
              frisians_reed_farmer= 1,
            },
          name= "frisians_reed_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 93,
          y= 174,
          inputs=             {
            },
        },
      [56] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 180,
          inputs=             {
            },
        },
      [57] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 93,
          y= 184,
          inputs=             {
            },
        },
      [58] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 87,
          y= 187,
          inputs=             {
            },
        },
      [59] =         {
          workers=             {
            },
          name= "frisians_port",
          wares=             {
            },
          soldiers=             {
            },
          x= 93,
          y= 178,
          inputs=             {
            },
        },
      [60] =         {
          workers=             {
            },
          name= "frisians_fortress",
          wares=             {
            },
          soldiers=             {
              ["0000"]= 12,
            },
          x= 92,
          y= 193,
          inputs=             {
            },
        },
      [61] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 89,
          y= 194,
          inputs=             {
            },
        },
      [62] =         {
          workers=             {
            },
          name= "frisians_port",
          wares=             {
            },
          soldiers=             {
            },
          x= 91,
          y= 198,
          inputs=             {
            },
        },
      [63] =         {
          workers=             {
              frisians_fisher= 1,
            },
          name= "frisians_fishers_house",
          wares=             {
            },
          soldiers=             {
            },
          x= 88,
          y= 200,
          inputs=             {
            },
        },
      [64] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 80,
          y= 168,
          inputs=             {
            },
        },
      [65] =         {
          workers=             {
              frisians_smelter= 1,
            },
          name= "frisians_furnace",
          wares=             {
            },
          soldiers=             {
            },
          x= 86,
          y= 148,
          inputs=             {
              gold_ore= 2,
              iron_ore= 5,
              coal= 4,
            },
        },
      [66] =         {
          workers=             {
              frisians_farmer= 1,
            },
          name= "frisians_farm",
          wares=             {
            },
          soldiers=             {
            },
          x= 83,
          y= 172,
          inputs=             {
            },
        },
      [67] =         {
          workers=             {
              frisians_charcoal_burner= 1,
            },
          name= "frisians_charcoal_kiln",
          wares=             {
            },
          soldiers=             {
            },
          x= 83,
          y= 151,
          inputs=             {
              clay= 2,
              log= 4,
            },
        },
    },
  details=     {
      [1] =         {
          tribe= "frisians",
          playerno= 1,
        },
    },
  roads=     {
      [1] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 143,
          dirs= "[[tr]],[[tl]]",
        },
      [2] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 141,
          dirs= "[[bl]],[[br]]",
        },
      [3] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 87,
          y= 141,
          dirs= "[[r]],[[r]]",
        },
      [4] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 89,
          y= 141,
          dirs= "[[tr]],[[tr]]",
        },
      [5] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 90,
          y= 139,
          dirs= "[[tr]],[[tr]]",
        },
      [6] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 144,
          dirs= "[[tr]],[[tr]],[[tl]]",
        },
      [7] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 86,
          y= 140,
          dirs= "[[br]],[[r]]",
        },
      [8] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 144,
          dirs= "[[br]],[[r]]",
        },
      [9] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 85,
          y= 142,
          dirs= "[[tr]],[[tr]]",
        },
      [10] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 139,
          dirs= "[[l]],[[bl]]",
        },
      [11] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 137,
          dirs= "[[br]],[[bl]]",
        },
      [12] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 137,
          dirs= "[[l]],[[l]]",
        },
      [13] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 135,
          dirs= "[[bl]],[[bl]]",
        },
      [14] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 135,
          dirs= "[[r]],[[r]]",
        },
      [15] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 135,
          dirs= "[[tr]],[[tr]]",
        },
      [16] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 133,
          dirs= "[[br]],[[bl]]",
        },
      [17] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 131,
          dirs= "[[br]],[[bl]]",
        },
      [18] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 131,
          dirs= "[[tr]],[[tr]]",
        },
      [19] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 131,
          dirs= "[[tl]],[[tl]]",
        },
      [20] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 127,
          dirs= "[[bl]],[[bl]]",
        },
      [21] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 125,
          dirs= "[[bl]],[[br]]",
        },
      [22] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 123,
          dirs= "[[br]],[[bl]]",
        },
      [23] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 123,
          dirs= "[[l]],[[l]]",
        },
      [24] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 123,
          dirs= "[[tl]],[[tl]],[[tr]]",
        },
      [25] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 120,
          dirs= "[[br]],[[br]],[[bl]]",
        },
      [26] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 123,
          dirs= "[[l]],[[l]]",
        },
      [27] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 125,
          dirs= "[[tr]],[[tl]]",
        },
      [28] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 133,
          dirs= "[[tl]],[[tl]]",
        },
      [29] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 130,
          dirs= "[[l]],[[bl]]",
        },
      [30] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 128,
          dirs= "[[bl]],[[bl]]",
        },
      [31] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 126,
          dirs= "[[br]],[[bl]]",
        },
      [32] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 126,
          dirs= "[[tr]],[[r]]",
        },
      [33] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 127,
          dirs= "[[tr]],[[tl]]",
        },
      [34] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 93,
          y= 129,
          dirs= "[[l]],[[tl]],[[tr]]",
        },
      [35] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 93,
          y= 131,
          dirs= "[[tr]],[[tl]]",
        },
      [36] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 94,
          y= 133,
          dirs= "[[tr]],[[tl]],[[l]]",
        },
      [37] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 133,
          dirs= "[[tr]],[[tr]]",
        },
      [38] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 94,
          y= 135,
          dirs= "[[tr]],[[tl]]",
        },
      [39] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 94,
          y= 135,
          dirs= "[[bl]],[[bl]]",
        },
      [40] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 133,
          dirs= "[[br]],[[bl]]",
        },
      [41] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 132,
          dirs= "[[br]],[[r]]",
        },
      [42] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 132,
          dirs= "[[l]],[[bl]]",
        },
      [43] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 130,
          dirs= "[[bl]],[[bl]]",
        },
      [44] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 135,
          dirs= "[[bl]],[[bl]]",
        },
      [45] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 139,
          dirs= "[[tr]],[[tr]]",
        },
      [46] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 93,
          y= 137,
          dirs= "[[l]],[[l]]",
        },
      [47] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 95,
          y= 140,
          dirs= "[[l]],[[tl]],[[l]]",
        },
      [48] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 141,
          dirs= "[[tr]],[[tl]]",
        },
      [49] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 143,
          dirs= "[[tr]],[[tr]]",
        },
      [50] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 145,
          dirs= "[[tr]],[[tr]]",
        },
      [51] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 147,
          dirs= "[[tr]],[[tr]]",
        },
      [52] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 149,
          dirs= "[[tr]],[[tr]]",
        },
      [53] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 151,
          dirs= "[[tr]],[[tr]]",
        },
      [54] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 153,
          dirs= "[[tr]],[[tr]]",
        },
      [55] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 153,
          dirs= "[[l]],[[bl]]",
        },
      [56] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 85,
          y= 154,
          dirs= "[[bl]],[[bl]]",
        },
      [57] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 85,
          y= 154,
          dirs= "[[l]],[[l]]",
        },
      [58] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 85,
          y= 151,
          dirs= "[[bl]],[[bl]],[[br]]",
        },
      [59] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 83,
          y= 154,
          dirs= "[[bl]],[[bl]]",
        },
      [60] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 84,
          y= 152,
          dirs= "[[bl]],[[bl]]",
        },
      [61] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 82,
          y= 156,
          dirs= "[[l]],[[l]]",
        },
      [62] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 88,
          y= 145,
          dirs= "[[bl]],[[bl]]",
        },
      [63] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 145,
          dirs= "[[tr]],[[tr]]",
        },
      [64] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 137,
          dirs= "[[tl]],[[tl]]",
        },
      [65] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 87,
          y= 147,
          dirs= "[[bl]],[[bl]]",
        },
      [66] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 84,
          y= 156,
          dirs= "[[bl]],[[bl]]",
        },
      [67] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 83,
          y= 158,
          dirs= "[[bl]],[[bl]]",
        },
      [68] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 82,
          y= 160,
          dirs= "[[bl]],[[br]]",
        },
      [69] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 82,
          y= 160,
          dirs= "[[l]],[[bl]],[[bl]]",
        },
      [70] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 82,
          y= 162,
          dirs= "[[br]],[[br]]",
        },
      [71] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 78,
          y= 162,
          dirs= "[[r]],[[r]]",
        },
      [72] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 77,
          y= 164,
          dirs= "[[tr]],[[tr]]",
        },
      [73] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 76,
          y= 161,
          dirs= "[[br]],[[r]]",
        },
      [74] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 75,
          y= 165,
          dirs= "[[r]],[[tr]]",
        },
      [75] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 80,
          y= 156,
          dirs= "[[l]],[[l]]",
        },
      [76] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 83,
          y= 164,
          dirs= "[[br]],[[br]]",
        },
      [77] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 84,
          y= 166,
          dirs= "[[br]],[[br]]",
        },
      [78] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 82,
          y= 167,
          dirs= "[[tr]],[[r]]",
        },
      [79] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 78,
          y= 156,
          dirs= "[[l]],[[l]]",
        },
      [80] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 76,
          y= 156,
          dirs= "[[l]],[[l]]",
        },
      [81] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 85,
          y= 168,
          dirs= "[[r]],[[tr]]",
        },
      [82] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 85,
          y= 168,
          dirs= "[[br]],[[br]]",
        },
      [83] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 167,
          dirs= "[[l]],[[bl]]",
        },
      [84] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 170,
          dirs= "[[br]],[[br]]",
        },
      [85] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 84,
          y= 171,
          dirs= "[[tr]],[[r]]",
        },
      [86] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 84,
          y= 152,
          dirs= "[[tr]],[[r]]",
        },
      [87] =         {
          workers=             {
              frisians_carrier= 1,
              frisians_reindeer= 1,
            },
          x= 86,
          y= 149,
          dirs= "[[bl]],[[bl]]",
        },
      [88] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 172,
          dirs= "[[br]],[[br]]",
        },
      [89] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 174,
          dirs= "[[br]],[[br]]",
        },
      [90] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 174,
          dirs= "[[bl]],[[l]]",
        },
      [91] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 86,
          y= 175,
          dirs= "[[tr]],[[r]]",
        },
      [92] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 176,
          dirs= "[[r]],[[tr]]",
        },
      [93] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 176,
          dirs= "[[br]],[[br]]",
        },
      [94] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 177,
          dirs= "[[r]],[[tr]]",
        },
      [95] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 175,
          dirs= "[[l]],[[bl]]",
        },
      [96] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 93,
          y= 175,
          dirs= "[[l]],[[l]],[[l]]",
        },
      [97] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 175,
          dirs= "[[tr]],[[tr]],[[tr]]",
        },
      [98] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 95,
          y= 172,
          dirs= "[[l]],[[l]],[[l]]",
        },
      [99] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 172,
          dirs= "[[tr]],[[tr]],[[tr]]",
        },
      [100] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 178,
          dirs= "[[br]],[[br]]",
        },
      [101] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 180,
          dirs= "[[r]],[[r]],[[tr]]",
        },
      [102] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 180,
          dirs= "[[br]],[[bl]]",
        },
      [103] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 93,
          y= 179,
          dirs= "[[l]],[[l]],[[bl]]",
        },
      [104] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 182,
          dirs= "[[bl]],[[br]]",
        },
      [105] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 182,
          dirs= "[[r]],[[r]]",
        },
      [106] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 87,
          y= 181,
          dirs= "[[br]],[[r]]",
        },
      [107] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 184,
          dirs= "[[br]],[[br]]",
        },
      [108] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 186,
          dirs= "[[bl]],[[bl]]",
        },
      [109] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 93,
          y= 185,
          dirs= "[[l]],[[bl]]",
        },
      [110] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 188,
          dirs= "[[bl]],[[br]]",
        },
      [111] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 190,
          dirs= "[[br]],[[bl]]",
        },
      [112] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 189,
          dirs= "[[br]],[[r]]",
        },
      [113] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 188,
          dirs= "[[r]],[[br]]",
        },
      [114] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 192,
          dirs= "[[bl]],[[br]]",
        },
      [115] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 194,
          dirs= "[[r]],[[r]]",
        },
      [116] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 92,
          y= 197,
          dirs= "[[tl]],[[tl]],[[tl]]",
        },
      [117] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 89,
          y= 195,
          dirs= "[[tr]],[[r]]",
        },
      [118] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 91,
          y= 199,
          dirs= "[[tr]],[[tr]]",
        },
      [119] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 93,
          y= 194,
          dirs= "[[bl]],[[br]],[[bl]]",
        },
      [120] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 200,
          dirs= "[[tr]],[[r]]",
        },
      [121] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 88,
          y= 201,
          dirs= "[[r]],[[tr]]",
        },
      [122] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 90,
          y= 135,
          dirs= "[[tl]],[[tl]]",
        },
      [123] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 80,
          y= 169,
          dirs= "[[tr]],[[r]],[[tr]]",
        },
      [124] =         {
          workers=             {
              frisians_carrier= 1,
            },
          x= 83,
          y= 173,
          dirs= "[[tr]],[[tr]]",
        },
    },
  flags=     {
      [1] =         {
          x= 89,
          y= 143,
          wares=             {
            },
        },
      [2] =         {
          x= 89,
          y= 143,
          wares=             {
            },
        },
      [3] =         {
          x= 87,
          y= 141,
          wares=             {
            },
        },
      [4] =         {
          x= 90,
          y= 139,
          wares=             {
            },
        },
      [5] =         {
          x= 91,
          y= 137,
          wares=             {
              fish= 1,
            },
        },
      [6] =         {
          x= 87,
          y= 144,
          wares=             {
            },
        },
      [7] =         {
          x= 86,
          y= 140,
          wares=             {
            },
        },
      [8] =         {
          x= 88,
          y= 145,
          wares=             {
              fish= 1,
            },
        },
      [9] =         {
          x= 85,
          y= 142,
          wares=             {
            },
        },
      [10] =         {
          x= 87,
          y= 139,
          wares=             {
            },
        },
      [11] =         {
          x= 87,
          y= 137,
          wares=             {
            },
        },
      [12] =         {
          x= 89,
          y= 137,
          wares=             {
            },
        },
      [13] =         {
          x= 88,
          y= 135,
          wares=             {
            },
        },
      [14] =         {
          x= 86,
          y= 135,
          wares=             {
            },
        },
      [15] =         {
          x= 89,
          y= 133,
          wares=             {
            },
        },
      [16] =         {
          x= 86,
          y= 133,
          wares=             {
            },
        },
      [17] =         {
          x= 86,
          y= 131,
          wares=             {
            },
        },
      [18] =         {
          x= 87,
          y= 129,
          wares=             {
            },
        },
      [19] =         {
          x= 88,
          y= 131,
          wares=             {
            },
        },
      [20] =         {
          x= 88,
          y= 127,
          wares=             {
            },
        },
      [21] =         {
          x= 88,
          y= 125,
          wares=             {
            },
        },
      [22] =         {
          x= 88,
          y= 123,
          wares=             {
              fish= 1,
            },
        },
      [23] =         {
          x= 90,
          y= 123,
          wares=             {
            },
        },
      [24] =         {
          x= 88,
          y= 120,
          wares=             {
            },
        },
      [25] =         {
          x= 88,
          y= 120,
          wares=             {
            },
        },
      [26] =         {
          x= 92,
          y= 123,
          wares=             {
            },
        },
      [27] =         {
          x= 92,
          y= 125,
          wares=             {
            },
        },
      [28] =         {
          x= 89,
          y= 133,
          wares=             {
            },
        },
      [29] =         {
          x= 90,
          y= 130,
          wares=             {
            },
        },
      [30] =         {
          x= 91,
          y= 128,
          wares=             {
            },
        },
      [31] =         {
          x= 91,
          y= 126,
          wares=             {
            },
        },
      [32] =         {
          x= 92,
          y= 125,
          wares=             {
            },
        },
      [33] =         {
          x= 92,
          y= 127,
          wares=             {
            },
        },
      [34] =         {
          x= 93,
          y= 129,
          wares=             {
            },
        },
      [35] =         {
          x= 93,
          y= 131,
          wares=             {
            },
        },
      [36] =         {
          x= 94,
          y= 133,
          wares=             {
            },
        },
      [37] =         {
          x= 92,
          y= 133,
          wares=             {
            },
        },
      [38] =         {
          x= 94,
          y= 135,
          wares=             {
            },
        },
      [39] =         {
          x= 93,
          y= 137,
          wares=             {
            },
        },
      [40] =         {
          x= 92,
          y= 135,
          wares=             {
            },
        },
      [41] =         {
          x= 91,
          y= 132,
          wares=             {
            },
        },
      [42] =         {
          x= 89,
          y= 133,
          wares=             {
            },
        },
      [43] =         {
          x= 92,
          y= 130,
          wares=             {
            },
        },
      [44] =         {
          x= 91,
          y= 137,
          wares=             {
              fish= 1,
            },
        },
      [45] =         {
          x= 92,
          y= 139,
          wares=             {
            },
        },
      [46] =         {
          x= 91,
          y= 137,
          wares=             {
              fish= 1,
            },
        },
      [47] =         {
          x= 95,
          y= 140,
          wares=             {
            },
        },
      [48] =         {
          x= 92,
          y= 141,
          wares=             {
            },
        },
      [49] =         {
          x= 91,
          y= 143,
          wares=             {
            },
        },
      [50] =         {
          x= 90,
          y= 145,
          wares=             {
            },
        },
      [51] =         {
          x= 89,
          y= 147,
          wares=             {
            },
        },
      [52] =         {
          x= 88,
          y= 149,
          wares=             {
            },
        },
      [53] =         {
          x= 87,
          y= 151,
          wares=             {
            },
        },
      [54] =         {
          x= 86,
          y= 153,
          wares=             {
            },
        },
      [55] =         {
          x= 85,
          y= 154,
          wares=             {
            },
        },
      [56] =         {
          x= 84,
          y= 156,
          wares=             {
            },
        },
      [57] =         {
          x= 83,
          y= 154,
          wares=             {
            },
        },
      [58] =         {
          x= 85,
          y= 151,
          wares=             {
            },
        },
      [59] =         {
          x= 82,
          y= 156,
          wares=             {
            },
        },
      [60] =         {
          x= 84,
          y= 152,
          wares=             {
            },
        },
      [61] =         {
          x= 80,
          y= 156,
          wares=             {
            },
        },
      [62] =         {
          x= 87,
          y= 147,
          wares=             {
            },
        },
      [63] =         {
          x= 89,
          y= 143,
          wares=             {
            },
        },
      [64] =         {
          x= 90,
          y= 135,
          wares=             {
            },
        },
      [65] =         {
          x= 86,
          y= 149,
          wares=             {
            },
        },
      [66] =         {
          x= 83,
          y= 158,
          wares=             {
            },
        },
      [67] =         {
          x= 82,
          y= 160,
          wares=             {
            },
        },
      [68] =         {
          x= 82,
          y= 162,
          wares=             {
              barley= 1,
            },
        },
      [69] =         {
          x= 80,
          y= 162,
          wares=             {
              barley= 1,
            },
        },
      [70] =         {
          x= 83,
          y= 164,
          wares=             {
            },
        },
      [71] =         {
          x= 78,
          y= 162,
          wares=             {
            },
        },
      [72] =         {
          x= 77,
          y= 164,
          wares=             {
            },
        },
      [73] =         {
          x= 76,
          y= 161,
          wares=             {
            },
        },
      [74] =         {
          x= 75,
          y= 165,
          wares=             {
            },
        },
      [75] =         {
          x= 78,
          y= 156,
          wares=             {
              barley= 1,
            },
        },
      [76] =         {
          x= 84,
          y= 166,
          wares=             {
            },
        },
      [77] =         {
          x= 85,
          y= 168,
          wares=             {
              barley= 2,
            },
        },
      [78] =         {
          x= 82,
          y= 167,
          wares=             {
            },
        },
      [79] =         {
          x= 76,
          y= 156,
          wares=             {
            },
        },
      [80] =         {
          x= 74,
          y= 156,
          wares=             {
            },
        },
      [81] =         {
          x= 86,
          y= 167,
          wares=             {
            },
        },
      [82] =         {
          x= 86,
          y= 170,
          wares=             {
            },
        },
      [83] =         {
          x= 86,
          y= 167,
          wares=             {
            },
        },
      [84] =         {
          x= 87,
          y= 172,
          wares=             {
            },
        },
      [85] =         {
          x= 84,
          y= 171,
          wares=             {
            },
        },
      [86] =         {
          x= 84,
          y= 152,
          wares=             {
            },
        },
      [87] =         {
          x= 86,
          y= 149,
          wares=             {
            },
        },
      [88] =         {
          x= 88,
          y= 174,
          wares=             {
            },
        },
      [89] =         {
          x= 89,
          y= 176,
          wares=             {
            },
        },
      [90] =         {
          x= 86,
          y= 175,
          wares=             {
            },
        },
      [91] =         {
          x= 86,
          y= 175,
          wares=             {
            },
        },
      [92] =         {
          x= 90,
          y= 175,
          wares=             {
            },
        },
      [93] =         {
          x= 90,
          y= 178,
          wares=             {
            },
        },
      [94] =         {
          x= 87,
          y= 177,
          wares=             {
            },
        },
      [95] =         {
          x= 90,
          y= 175,
          wares=             {
            },
        },
      [96] =         {
          x= 93,
          y= 175,
          wares=             {
              reed= 1,
            },
        },
      [97] =         {
          x= 92,
          y= 172,
          wares=             {
              reed= 2,
            },
        },
      [98] =         {
          x= 95,
          y= 172,
          wares=             {
            },
        },
      [99] =         {
          x= 93,
          y= 169,
          wares=             {
            },
        },
      [100] =         {
          x= 91,
          y= 180,
          wares=             {
            },
        },
      [101] =         {
          x= 93,
          y= 179,
          wares=             {
            },
        },
      [102] =         {
          x= 91,
          y= 182,
          wares=             {
            },
        },
      [103] =         {
          x= 93,
          y= 179,
          wares=             {
            },
        },
      [104] =         {
          x= 91,
          y= 184,
          wares=             {
            },
        },
      [105] =         {
          x= 89,
          y= 182,
          wares=             {
            },
        },
      [106] =         {
          x= 87,
          y= 181,
          wares=             {
            },
        },
      [107] =         {
          x= 92,
          y= 186,
          wares=             {
            },
        },
      [108] =         {
          x= 91,
          y= 188,
          wares=             {
            },
        },
      [109] =         {
          x= 93,
          y= 185,
          wares=             {
            },
        },
      [110] =         {
          x= 91,
          y= 190,
          wares=             {
            },
        },
      [111] =         {
          x= 91,
          y= 192,
          wares=             {
            },
        },
      [112] =         {
          x= 89,
          y= 189,
          wares=             {
            },
        },
      [113] =         {
          x= 88,
          y= 188,
          wares=             {
            },
        },
      [114] =         {
          x= 91,
          y= 194,
          wares=             {
            },
        },
      [115] =         {
          x= 93,
          y= 194,
          wares=             {
            },
        },
      [116] =         {
          x= 92,
          y= 197,
          wares=             {
            },
        },
      [117] =         {
          x= 89,
          y= 195,
          wares=             {
            },
        },
      [118] =         {
          x= 91,
          y= 199,
          wares=             {
            },
        },
      [119] =         {
          x= 93,
          y= 194,
          wares=             {
            },
        },
      [120] =         {
          x= 90,
          y= 200,
          wares=             {
            },
        },
      [121] =         {
          x= 88,
          y= 201,
          wares=             {
            },
        },
      [122] =         {
          x= 89,
          y= 133,
          wares=             {
            },
        },
      [123] =         {
          x= 80,
          y= 169,
          wares=             {
            },
        },
      [124] =         {
          x= 83,
          y= 173,
          wares=             {
            },
        },
    },
}

function place_flags(eco)

   for i = 1, #eco.flags do
      local flag = p1:place_flag(map:get_field(eco.flags[i].x, eco.flags[i].y),true)
      for ware,count in pairs(eco.flags[i].wares) do
         flag:set_wares(ware,count)
      end
   end
end

function place_roads(eco)
   for i = 1, #eco.roads do
      local command = string.format("road = p1:place_road(\"normal\", map:get_field(%i,%i).immovable, %s ,true)", eco.roads[i].x, eco.roads[i].y, eco.roads[i].dirs)
      local f = assert (load (command))
      f()
      -- Second carrier can't be placed currently, so we just fake a carrier
      worker = (p1.tribe_name.."_carrier")
      road:set_workers(worker,1)
   end
end

function place_buildings(eco)

   for i = 1, #eco.buildings do
      building = p1:place_building(eco.buildings[i].name, map:get_field(eco.buildings[i].x, eco.buildings[i].y), false, true)

      if eco.buildings[i].inputs then
         for ware,count in pairs(eco.buildings[i].inputs) do
            building:set_inputs(ware,count)
         end
      end

      if eco.buildings[i].workers then
         local up = {}
         for worker,count in pairs(eco.buildings[i].workers) do
            if count == 0 then
               up[#up+1] = worker
            elseif count > 1 and #up > 0 and not building.descr.type_name == "warehouse" then
               for i = 1, count - 1 do
                  building:set_workers(up[i],1)
               end
               building:set_workers(worker,1)
            else
               building:set_workers(worker,1)
            end
         end
      end

      if eco.buildings[i].wares then
         for ware,count in pairs(eco.buildings[i].wares) do
            building:set_wares(ware,count)
         end
      end

      if eco.buildings[i].soldiers then
         for soldier,count in pairs(eco.buildings[i].soldiers) do
            building:set_soldiers({soldier:sub(1,1),soldier:sub(2,2),soldier:sub(3,3),soldier:sub(4,4)}, count)
         end
      end
   end

end

place_flags(eco)
place_roads(eco)
place_buildings(eco)

-- End of autogenerated section

local soldiers = {}
local max_takeover_soldiers = {300, 200, 100}
local total_soldiers = 0
for descr,n in pairs(campaign_data) do total_soldiers = total_soldiers + n end
if total_soldiers > max_takeover_soldiers[difficulty] then total_soldiers = max_takeover_soldiers[difficulty] end
while total_soldiers > 0 do
   local key1 = math.random(0, 2)
   local key2 = math.random(0, 6)
   local key3 = math.random(0, 2)
   for descr,n in pairs(campaign_data) do
      if descr == (key1 .. key2 .. key3) and n > 0 and not (key1 == 0 and key2 == 0 and key3 == 0) then
         if n < total_soldiers then
            soldiers[{key1, key2, key3, 0}] = n
            total_soldiers = total_soldiers - n
         else
            soldiers[{key1, key2, key3, 0}] = total_soldiers
            total_soldiers = 0
         end
         campaign_data[descr] = nil
         break
      end
   end
end
p1:get_buildings("frisians_headquarters")[1]:set_soldiers(soldiers)
