-- Do not edit this file - it is automatically generated
-- by utils/update_authors.py from the JSON files.
translators = {{"Arabic",{"abdXelrhman","m-abudrais","someone",}},{"Asturian",{"Xuacu Saturio",}},}