#! /bin/sh

if [ ! -f utils/spurious_source_code/leading_whitespace_checker ]; then
	echo "WARNING: utils/spurious_source_code/leading_whitespace_checker does not exist!"
	echo "WARNING:    Go to utils/spurious_source_code and build it with make!"
	echo "WARNING:    Leading whitespace will not be checked!"
fi

REGEXPS_FILE="/tmp/spurious_source_code_regexps"
rm -f $REGEXPS_FILE
for r in utils/spurious_source_code/regexps/*; do
	[[ -d $r ]] && if [ ! -f $r/disabled ]; then
		cat $r/regexps >> $REGEXPS_FILE
	fi
done
for i in $(find src -name *.h -o -name *.cc); do
	egrep --color --with-filename --line-number -f $REGEXPS_FILE $i;
	utils/detect_spurious_indentation.py $i;
	if [ -f utils/spurious_source_code/leading_whitespace_checker ]; then
		utils/spurious_source_code/leading_whitespace_checker $i
	fi
done
rm -f $REGEXPS_FILE
