Import('*')

SRC=simpleglob("*.cc")

scripting=srcenv.StaticLibrary(target='scripting', source=SRC)

###########################################################################
#                                  Tests                                  #
###########################################################################

Return('scripting')

