Import('*')


pluto = SConscript("pluto/SConscript")

SRC=simpleglob("*.cc") + [pluto]

scripting=srcenv.StaticLibrary(target='scripting', source=SRC)

###########################################################################
#                                  Tests                                  #
###########################################################################

Return('scripting')

