Import('*')


# pluto = SConscript("pluto/SConscript")

SRC=simpleglob("*.cc") + ["pluto/pdep.c", "pluto/pluto.c", "pluto/lzio.c"]

scripting=srcenv.StaticLibrary(target='scripting', source=SRC)

###########################################################################
#                                  Tests                                  #
###########################################################################

Return('scripting')

