name: Feature Request
description: Suggest an idea for this project.
labels: enhancement

body:
  - type: textarea
    id: summary
    attributes:
      label: Describe the Problem
      description: A clear and concise description of what the problem is.
      placeholder: e.g. I'm always frustrated when …
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Steps
      description: How this feature might be implemented.
      placeholder: |
        - [ ] Add backend logic
        - [ ] Add multiplayer bindings
        - [ ] Add savegame compatibility
        - [ ] Add frontend

