Import('env')

from Distribute import distadd, instadd

instadd(env, 'campaigns/*.wmf')
instadd(env, 'campaigns/cconfig')

distadd(env, 'campaigns/SConscript')
distadd(env, 'campaigns/*.wmf')
distadd(env, 'campaigns/cconfig')
