Import('env')

from Distribute import distadd, instadd

instadd(env, 'campaigns/*.wmf', 'campaigns')
instadd(env, 'campaigns/cconfig', 'campaigns')

distadd(env, 'campaigns/SConscript')
distadd(env, 'campaigns/*.wmf')
distadd(env, 'campaigns/cconfig', 'campaigns')
