Import('*')

SRC=simpleglob("*.cc")

economy=srcenv.StaticLibrary(target='economy', source=SRC)

###########################################################################
#                                  Tests                                  #
###########################################################################
SConscript("test/SConscript", "tests BUILDDIR testEnv simpleglob economy")


Return('economy')

