Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/explicit_compare_with_boolean_constant/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/explicit_compare_with_boolean_constant/allowed')
distadd(env, 'utils/spurious_source_code/regexps/explicit_compare_with_boolean_constant/documentation')
distadd(env, 'utils/spurious_source_code/regexps/explicit_compare_with_boolean_constant/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/explicit_compare_with_boolean_constant/regexps')

