Import('*')

SRC=["pdep.cc",  "pluto.cc"]

pluto=srcenv.StaticLibrary(target='pluto', source=SRC)

###########################################################################
#                                  Tests                                  #
###########################################################################

Return('pluto')

