# # # # # # # # # # # # # # # # # # # # # # # # #
#                                               #
#          PLEASE DEFINE BUILDTYPE HERE         #
#                                               #
# # # # # # # # # # # # # # # # # # # # # # # # #


#### Buildtype ####
BUILD=release
#Build=debug-no-parachute
#Build=debug-slow
#Build=debug

#### Version #### // Needed for 'make dist'
Version="Build18"

