-- This file is generated by utils/update_authors.py.
-- The locale data is managed in Transifex.

return {
	-- Locales are identified by their ISO code.
 	en = {
		-- Used to display the locale in the Options menu.
		name = "English",

		-- Defines the language's position on the list in the Options menu.
		sort_name = "English",

		-- The font set used, including the script's direction. See i18n/fonts.lua
		font = "default"
	},

	ar = {
		name = "العربية",
		sort_name = "Al-ʿArabiyyah",
		font = "arabic"
	},

	ast = {
		name = "Asturianu",
		sort_name = "Asturianu",
		font = "default"
	},

	bg = {
		name = "Български",
		sort_name = "Balgarski",
		font = "default"
	},

	ca = {
		name = "Català",
		sort_name = "Catala",
		font = "default"
	},

	cs = {
		name = "Čeština",
		sort_name = "Cestina",
		font = "default"
	},

	da = {
		name = "Dansk",
		sort_name = "Dansk",
		font = "default"
	},

	de = {
		name = "Deutsch",
		sort_name = "Deutsch",
		font = "default"
	},

	el = {
		name = "Ελληνικά",
		sort_name = "Ellinika",
		font = "default"
	},

	en_AU = {
		name = "Australian English",
		sort_name = "English (Australia)",
		font = "default"
	},

	en_CA = {
		name = "Canadian English",
		sort_name = "English (Canada)",
		font = "default"
	},

	en_GB = {
		name = "British English",
		sort_name = "English (Great Britain)",
		font = "default"
	},

	en_US = {
		name = "US American English",
		sort_name = "English (USA)",
		font = "default"
	},

	eo = {
		name = "Esperanto",
		sort_name = "Esperanto",
		font = "default"
	},

	es = {
		name = "Español",
		sort_name = "Espanol",
		font = "default"
	},

	es_CO = {
		name = "Español colombiano",
		sort_name = "Espanol colombiano",
		font = "default"
	},

	et = {
		name = "Eesti keel",
		sort_name = "Eesti keel",
		font = "default"
	},

	eu = {
		name = "Euskara",
		sort_name = "Euskara",
		font = "default"
	},

	fa = {
		name = "فارسی",
		sort_name = "Farsi",
		font = "arabic"
	},

	fi = {
		name = "Suomi",
		sort_name = "Suomi",
		font = "default"
	},

	fr = {
		name = "Français",
		sort_name = "Francais",
		font = "default"
	},

	gd = {
		name = "Gàidhlig",
		sort_name = "Gaidhlig",
		font = "default"
	},

	gl = {
		name = "Galego",
		sort_name = "Galego",
		font = "default"
	},

	he = {
		name = "עברית",
		sort_name = "Ivrit",
		font = "hebrew"
	},

	hi = {
		name = "हिन्दी",
		sort_name = "Hindi",
		font = "devanagari"
	},

	hr = {
		name = "Hrvatski",
		sort_name = "Hrvatski",
		font = "default"
	},

	hu = {
		name = "Magyar",
		sort_name = "Magyar",
		font = "default"
	},

	ia = {
		name = "Interlingua",
		sort_name = "Interlingua",
		font = "default"
	},

	id = {
		name = "Bahasa Indonesia",
		sort_name = "Indonesia",
		font = "default"
	},

	it = {
		name = "Italiano",
		sort_name = "Italiano",
		font = "default"
	},

	ja = {
		name = "日本語",
		sort_name = "Nihongo",
		font = "cjk"
	},

	jv = {
		name = "Basa jawa",
		sort_name = "Jawa",
		font = "default"
	},

	ka = {
		name = "ქართული",
		sort_name = "Kartuli",
		font = "default"
	},

	ko = {
		name = "한국어",
		sort_name = "Hangug-eo",
		font = "cjk"
	},

	la = {
		name = "Lingua latīna",
		sort_name = "Latina",
		font = "default"
	},

	lt = {
		name = "Lietuvių",
		sort_name = "Lietuviu",
		font = "default"
	},

	mr = {
		name = "मराठी",
		sort_name = "Marathi",
		font = "devanagari"
	},

	ms = {
		name = "بهاس ملايو",
		sort_name = "Melayu",
		font = "arabic"
	},

	my = {
		name = "မြန်မာစ",
		sort_name = "Myanma",
		font = "myanmar"
	},

	nb = {
		name = "Norsk (Bokmål)",
		sort_name = "Norsk (Bokmal)",
		font = "default"
	},

	nds = {
		name = "Plattdütsch",
		sort_name = "Plattdutsch",
		font = "default"
	},

	nl = {
		name = "Nederlands",
		sort_name = "Nederlands",
		font = "default"
	},

	nn = {
		name = "Nynorsk",
		sort_name = "Norsk (Nynorsk)",
		font = "default"
	},

	oc = {
		name = "Occitan",
		sort_name = "Occitan",
		font = "default"
	},

	pl = {
		name = "Polski",
		sort_name = "Polski",
		font = "default"
	},

	pt = {
		name = "Português",
		sort_name = "Portugues",
		font = "default"
	},

	pt_BR = {
		name = "Português do Brasil",
		sort_name = "Portugues (Brasil)",
		font = "default"
	},

	ro = {
		name = "Română",
		sort_name = "Romana",
		font = "default"
	},

	ru = {
		name = "Русский",
		sort_name = "Russky",
		font = "default"
	},

	rw = {
		name = "Kinyarwanda",
		sort_name = "Kinyarwanda",
		font = "default"
	},

	si = {
		name = "සිංහල",
		sort_name = "Simhala",
		font = "sinhala"
	},

	sk = {
		name = "Slovenčina",
		sort_name = "Slovencina",
		font = "default"
	},

	sl = {
		name = "Slovenski jezik",
		sort_name = "Slovenski",
		font = "default"
	},

	sr = {
		name = "српски",
		sort_name = "Srpski",
		font = "default"
	},

	sv = {
		name = "Svenska",
		sort_name = "Svenska",
		font = "default"
	},

	tr = {
		name = "Türkçe",
		sort_name = "Turkce",
		font = "default"
	},

	uk = {
		name = "українська мова",
		sort_name = "Ukrayinska",
		font = "default"
	},

	vi = {
		name = "Tiếng Việt",
		sort_name = "Viet",
		font = "default"
	},

	zh_CN = {
		name = "简体中文",
		sort_name = "Jianti Zhongwen",
		font = "cjk"
	},

	zh_TW = {
		name = "繁體中文",
		sort_name = "Fanti Zhongwen",
		font = "cjk"
	},
}
