
Import("*")

tenv = testEnv.Clone()
tenv.AppendUnique(LIBS=[economy])

# tenv.addUnitTest("test_economy", simpleglob("*.cc") + [ '../../../../' + BUILDDIR +'/log.o'])
tenv.addUnitTest("test_economy", simpleglob("*.cc"))

