Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/illegal_character_before_opening_brace/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_before_opening_brace/allowed')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_before_opening_brace/documentation')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_before_opening_brace/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_before_opening_brace/redundant_with_whitespace_checker')
distadd(env, 'utils/spurious_source_code/regexps/illegal_character_before_opening_brace/regexps')

