Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/trailing_whitespace/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/trailing_whitespace/documentation')
distadd(env, 'utils/spurious_source_code/regexps/trailing_whitespace/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/trailing_whitespace/regexps')

