Import('*')

SRC=simpleglob("*.cc")

srcenv.Append(INDENTLIST=[
	'io/filesystem/disk_filesystem.h',
	'io/filesystem/disk_filesystem.cc',
	'io/filesystem/filesystem.h',
	'io/filesystem/filesystem_exceptions.h',
	'io/filesystem/layered_filesystem.h',
	'io/filesystem/layered_filesystem.cc',
	'io/filesystem/zip_exceptions.h',
	])

filesystem=srcenv.StaticLibrary(target='filesystem', source=SRC)

###########################################################################
#                                  Tests                                  #
###########################################################################
SConscript("test/SConscript", "tests BUILDDIR testEnv simpleglob filesystem")

Return('filesystem')

