Import('*')
from Distribute import distadd, instadd

distadd(env, 'po/*')
instadd(env, 'locale/*', 'locale')

#will be executed from base dir!
buildlocale=PhonyTarget("buildlocale", 'utils/buildlocale.py')

Return('buildlocale')

