Import('*')
from Distribute import distadd, instadd

distadd(env, 'po/*')
instadd(env, 'locale/*', filetype='locale')

#will be executed from base dir!
buildlocale=PhonyTarget("buildlocale", 'python ./utils/buildlocale.py')

Return('buildlocale')

