#!/bin/bash
FILE=cppcheck_report.xhtml
echo "<?xml version=\"1.0\" encoding=\"us-ascii\"?>"                                                                     >  $FILE
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">" >> $FILE
echo "<html xmlns=\"http://www.w3.org/1999/xhtml\">"                                                                     >> $FILE
echo "<head><title>cppcheck error report for Widelands C++ source code</title></head>"                                   >> $FILE
echo "<body>"                                                                                                            >> $FILE
echo "<div>"                                                                                                             >> $FILE
cppcheck --all --quiet --style --unused-functions src 2>&1 | sed "s@^\[\(.*\):\([[:digit:]]\+\)\]: \(.*\)\$@<a href=\"http://widelands.svn.sourceforge.net/viewvc/widelands/trunk/\1\?view=markup#l_\2\">\1:\2</a>: \3<br/>@" >> $FILE
echo "</div>"                                                                                                            >> $FILE
echo "</body>"                                                                                                           >> $FILE
echo "</html>"                                                                                                           >> $FILE
