Import('env')
from Distribute import *

distadd(env, 'utils/SConscript')
distadd(env, 'utils/create_cppcheck_report')
distadd(env, 'utils/*.py')
distadd(env, 'utils/*.sh')
distadd(env, 'utils/')

Export('env')
SConscript('spurious_source_code/SConscript')
SConscript('syncstream/SConscript')

