#!/usr/bin/env python
# encoding: utf-8

import codecs
import json
import os.path
import sys

# This script collects translator credits from the JSON files in
# ../txts/translators.
# It then collects all other contributors from ../txts/developers.json,
# adds the translators at the hook "Translators"
# and writes everything to ./txts/developers.lua


base_path = os.path.abspath(os.path.join(os.path.dirname(__file__),os.path.pardir))

print("Reading translators from JSON:")

source_path = os.path.normpath(base_path + "/txts/translators")

if (not os.path.isdir(source_path)):
	print("Error: Path " + source_path + " not found.")
	sys.exit(1)

# Each language's translators live in a separate file, so we list the dir
source_files = os.listdir(source_path)

lua_translators = ""
for source_filename in source_files:
	# Only json files, and not the template file please
	if source_filename.endswith(".json") and source_filename != "translators.json":
		source_file = open(source_path + "/" + source_filename, "r")
		translators = json.load(source_file)
		# Make sure we don't pick up untranslated stuff
		if translators["locale-translators"]["translator-list"] != 'translator-credits':
                        msg = "- Adding translators for " + translators["locale-translators"]["your-language-name"]
			print(msg.encode('ascii', errors='xmlcharrefreplace'))
			lua_translators += '{' # entry
			lua_translators += 'subheading = "' + translators["locale-translators"]["your-language-name"] + '",'

			lua_translators += 'members = {' # members
			for transl_name in translators["locale-translators"]["translator-list"].split("\n"):
				lua_translators += '"' + transl_name + '",'
			lua_translators += "}," # members
			lua_translators += "}," # entry


print("Reading developers from JSON")
source_path = os.path.normpath(base_path + "/txts")

if (not os.path.isdir(source_path)):
	print("Error: Path " + source_path + " not found.")
	sys.exit(1)

source_file = open(source_path + "/developers.json", "r")
developers = json.load(source_file)["developers"]

lua_string = """-- Do not edit this file - it is automatically generated
-- by utils/update_authors.py from developers.json.
"""
lua_string += "function developers() return {" # developers

for category in developers:
	print("- Adding " + category["heading"])
	lua_string += '{' # category
	lua_string += 'heading = _"' + category["heading"] + '",' # This will be localized
	lua_string += 'image = "' + category["image"] + '",'

	lua_string += 'entries = {' # entries
	if category["heading"] == "Translators": # Hook for adding the translators parsed above
		lua_string += lua_translators
	else:
		for subcategory in category["entries"]:
			lua_string += '{' # entry
			if 'subheading' in subcategory:
				lua_string += 'subheading = _"' + subcategory["subheading"] + '",' # This will be localized

			lua_string += 'members = {' # members
			for member in subcategory["members"]:
				lua_string += '"' + member + '",'
			lua_string += "}," # members

			lua_string += "}," # entry
	lua_string += "}," # entries

	lua_string += "}," # category
lua_string += "} end" # developers

print("Writing developers")
dest_filename = "developers.lua"
dest_filepath = source_path + "/" + dest_filename
dest_file = codecs.open(dest_filepath, encoding='utf-8', mode='w')
dest_file.write(lua_string)
print("Done.")
