Import('*')

SRC=simpleglob("*.cc")

srcenv.Append(INDENTLIST=[
	'sound/fxset.h',
	'sound/fxset.cc',
	'sound/songset.h',
	'sound/songset.cc',
	'sound/sound_handler.h',
	'sound/sound_handler.cc',
	])

lib=srcenv.StaticLibrary(target='sound', source=SRC)
Return('lib')

