Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/SDL_integer_types_in_non_SDL_dependent_code/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/SDL_integer_types_in_non_SDL_dependent_code/allowed')
distadd(env, 'utils/spurious_source_code/regexps/SDL_integer_types_in_non_SDL_dependent_code/documentation')
distadd(env, 'utils/spurious_source_code/regexps/SDL_integer_types_in_non_SDL_dependent_code/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/SDL_integer_types_in_non_SDL_dependent_code/regexps')

