Import('env')

from Distribute import distadd

distadd(env, 'build/scons-tools/codecheck/SConscript')
distadd(env, 'build/scons-tools/codecheck/*.py')
distadd(env, 'build/scons-tools/codecheck/rules')

