void f () {
	float A;A; float a;a;
	float B;B; float b;b;
	float C;C; float c;c;
	float D;D; float d;d;
	float E;E; float e;e;
	float F;F; float f;f;
	float G;G; float g;g;
	float H;H; float h;h;
	float I;I; float i;i;
	float J;J; float j;j;
	float K;K; float k;k;
	float L;L; float l;l;
	float M;M; float m;m;
	float N;N; float n;n;
	float O;O; float o;o;
	float P;P; float p;p;
	float Q;Q; float q;q;
	float R;R; float r;r;
	float S;S; float s;s;
	float T;T; float t;t;
	float U;U; float u;u;
	float V;V; float v;v;
	float W;W; float w;w;
	float X;X; float x;x;
	float Y;Y; float y;y;
	float Z;Z; float z;z;
	float _;_;++_;--_;* &_;
	float * ptr;&*ptr;
}
