char a=a^a%a/a*a-a+a, A=A^A%A/A*A-A+A, b=b^b%b/b*b-b+b, B=B^B%B/B*B-B+B;
char c=c^c%c/c*c-c+c, C=C^C%C/C*C-C+C, d=d^d%d/d*d-d+d, D=D^D%D/D*D-D+D;
char e=e^e%e/e*e-e+e, E=E^E%E/E*E-E+E, f=f^f%f/f*f-f+f, F=F^F%F/F*F-F+F;
char g=g^g%g/g*g-g+g, G=G^G%G/G*G-G+G, h=h^h%h/h*h-h+h, H=H^H%H/H*H-H+H;
char i=i^i%i/i*i-i+i, I=I^I%I/I*I-I+I, j=j^j%j/j*j-j+j, J=J^J%J/J*J-J+J;
char k=k^k%k/k*k-k+k, K=K^K%K/K*K-K+K, l=l^l%l/l*l-l+l, L=L^L%L/L*L-L+L;
char m=m^m%m/m*m-m+m, M=M^M%M/M*M-M+M, n=n^n%n/n*n-n+n, N=N^N%N/N*N-N+N;
char o=o^o%o/o*o-o+o, O=O^O%O/O*O-O+O, p=p^p%p/p*p-p+p, P=P^P%P/P*P-P+P;
char q=q^q%q/q*q-q+q, Q=Q^Q%Q/Q*Q-Q+Q, r=r^r%r/r*r-r+r, R=R^R%R/R*R-R+R;
char s=s^s%s/s*s-s+s, S=S^S%S/S*S-S+S, t=t^t%t/t*t-t+t, T=T^T%T/T*T-T+T;
char u=u^u%u/u*u-u+u, U=U^U%U/U*U-U+U, v=v^v%v/v*v-v+v, V=V^V%V/V*V-V+V;
char w=w^w%w/w*w-w+w, W=W^W%W/W*W-W+W, x=x^x%x/x*x-x+x, X=X^X%X/X*X-X+X;
char y=y^y%y/y*y-y+y, Y=Y^Y%Y/Y*Y-Y+Y, z=z^z%z/z*z-z+z, Z=Z^Z%Z/Z*Z-Z+Z;
char _=_^_%_/_*_-_+_, x0=010^010%010/010*010-010+010, x1=1%1/1*1-1+1;
char x2=2^2%2/2*2-2+2, x3=3^3%3/3*3-3+3, x4=4^4%4/4*4-4+4, x5=5^5%5/5*5-5+5;
char x6=6^6%6/6*6-6+6, x7=7^7%7/7*7-7+7, x8=8^8%8/8*8-8+8, x9=9^9%9/9*9-9+9;
char const * str ="";
char ch =' ';
void func() {
	a^=a%=a/=a*=a-=a+=a; A^=A%=A/=A*=A-=A+=A;
	b^=b%=b/=b*=b-=b+=b; B^=B%=B/=B*=B-=B+=B;
	c^=c%=c/=c*=c-=c+=c; C^=C%=C/=C*=C-=C+=C;
	d^=d%=d/=d*=d-=d+=d; D^=D%=D/=D*=D-=D+=D;
	e^=e%=e/=e*=e-=e+=e; E^=E%=E/=E*=E-=E+=E;
	f^=f%=f/=f*=f-=f+=f; F^=F%=F/=F*=F-=F+=F;
	g^=g%=g/=g*=g-=g+=g; G^=G%=G/=G*=G-=G+=G;
	h^=h%=h/=h*=h-=h+=h; H^=H%=H/=H*=H-=H+=H;
	i^=i%=i/=i*=i-=i+=i; I^=I%=I/=I*=I-=I+=I;
	j^=j%=j/=j*=j-=j+=j; J^=J%=J/=J*=J-=J+=J;
	k^=k%=k/=k*=k-=k+=k; K^=K%=K/=K*=K-=K+=K;
	l^=l%=l/=l*=l-=l+=l; L^=L%=L/=L*=L-=L+=L;
	m^=m%=m/=m*=m-=m+=m; M^=M%=M/=M*=M-=M+=M;
	n^=n%=n/=n*=n-=n+=n; N^=N%=N/=N*=N-=N+=N;
	o^=o%=o/=o*=o-=o+=o; O^=O%=O/=O*=O-=O+=O;
	p^=p%=p/=p*=p-=p+=p; P^=P%=P/=P*=P-=P+=P;
	q^=q%=q/=q*=q-=q+=q; Q^=Q%=Q/=Q*=Q-=Q+=Q;
	r^=r%=r/=r*=r-=r+=r; R^=R%=R/=R*=R-=R+=R;
	s^=s%=s/=s*=s-=s+=s; S^=S%=S/=S*=S-=S+=S;
	t^=t%=t/=t*=t-=t+=t; T^=T%=T/=T*=T-=T+=T;
	u^=u%=u/=u*=u-=u+=u; U^=U%=U/=U*=U-=U+=U;
	v^=v%=v/=v*=v-=v+=v; V^=V%=V/=V*=V-=V+=V;
	w^=w%=w/=w*=w-=w+=w; W^=W%=W/=W*=W-=W+=W;
	x^=x%=x/=x*=x-=x+=x; X^=X%=X/=X*=X-=X+=X;
	y^=y%=y/=y*=y-=y+=y; Y^=Y%=Y/=Y*=Y-=Y+=Y;
	z^=z%=z/=z*=z-=z+=z; Z^=Z%=Z/=Z*=Z-=Z+=Z;
	_^=_%=_/=_*=_-=_+=_;
}
typedef float type_a; type_a& aa = aa; typedef float type_A; type_A& AA = AA;
typedef float type_b; type_b& bb = bb; typedef float type_B; type_B& BB = BB;
typedef float type_c; type_c& cc = cc; typedef float type_C; type_C& CC = AA;
typedef float type_d; type_d& dd = dd; typedef float type_D; type_D& DD = DD;
typedef float type_e; type_e& ee = ee; typedef float type_E; type_E& EE = EE;
typedef float type_f; type_f& ff = ff; typedef float type_F; type_F& FF = FF;
typedef float type_g; type_g& gg = gg; typedef float type_G; type_G& GG = GG;
typedef float type_h; type_h& hh = hh; typedef float type_H; type_H& HH = HH;
typedef float type_i; type_i& ii = ii; typedef float type_I; type_I& II = II;
typedef float type_j; type_j& jj = jj; typedef float type_J; type_J& JJ = JJ;
typedef float type_k; type_k& kk = kk; typedef float type_K; type_K& KK = KK;
typedef float type_l; type_l& ll = ll; typedef float type_L; type_L& LL = LL;
typedef float type_m; type_m& mm = mm; typedef float type_M; type_M& MM = MM;
typedef float type_n; type_n& nn = nn; typedef float type_N; type_N& NN = NN;
typedef float type_o; type_o& oo = oo; typedef float type_O; type_O& OO = OO;
typedef float type_p; type_p& pp = pp; typedef float type_P; type_P& PP = PP;
typedef float type_q; type_q& qq = qq; typedef float type_Q; type_Q& QQ = QQ;
typedef float type_r; type_r& rr = rr; typedef float type_R; type_R& RR = RR;
typedef float type_s; type_s& ss = ss; typedef float type_S; type_S& SS = SS;
typedef float type_t; type_t& tt = tt; typedef float type_T; type_T& TT = TT;
typedef float type_u; type_u& uu = uu; typedef float type_U; type_U& UU = UU;
typedef float type_v; type_v& vv = vv; typedef float type_V; type_V& VV = VV;
typedef float type_w; type_w& ww = ww; typedef float type_W; type_W& WW = WW;
typedef float type_x; type_x& xx = xx; typedef float type_X; type_X& XX = XX;
typedef float type_y; type_y& yy = yy; typedef float type_Y; type_Y& YY = YY;
typedef float type_z; type_z& zz = zz; typedef float type_Z; type_Z& ZZ = ZZ;
type_a* aaa; type_b* bbb; type_c* ccc; type_d* ddd; type_e* eee; type_f* fff;
type_g* ggg; type_h* hhh; type_i* iii; type_j* jjj; type_k* kkk; type_l* lll;
type_m* mmm; type_n* nnn; type_o* ooo; type_p* ppp; type_q* qqq; type_r* rrr;
type_s* sss; type_t* ttt; type_u* uuu; type_v* vvv; type_w* www; type_x* xxx;
type_y* yyy; type_z* zzz;
type_A* AAA; type_B* BBB; type_C* CCC; type_D* DDD; type_E* EEE; type_F* FFF;
type_G* GGG; type_H* HHH; type_I* III; type_J* JJJ; type_K* KKK; type_L* LLL;
type_M* MMM; type_N* NNN; type_O* OOO; type_P* PPP; type_Q* QQQ; type_R* RRR;
type_S* SSS; type_T* TTT; type_U* UUU; type_V* VVV; type_W* WWW; type_X* XXX;
type_Y* YYY; type_Z* ZZZ;
