Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/explicit_this_dereference_and_component_selection/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/explicit_this_dereference_and_component_selection/allowed')
distadd(env, 'utils/spurious_source_code/regexps/explicit_this_dereference_and_component_selection/documentation')
distadd(env, 'utils/spurious_source_code/regexps/explicit_this_dereference_and_component_selection/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/explicit_this_dereference_and_component_selection/regexps')
