macro(_include_directories TARGET DIR SYSTEM)
  if ("${SYSTEM}" EQUAL "TRUE")
    include_directories(SYSTEM "${DIR}")
    message(STATUS "including ${DIR} as OLDSCHOOL SYSTEM")
  else ("${SYSTEM}" EQUAL "TRUE")
    include_directories("${DIR}")
    message(STATUS "including ${DIR} as OLDSCHOOL")
  endif ("${SYSTEM}" EQUAL "TRUE")
endmacro(_include_directories TARGET DIR SYSTEM)
