Import('env')
from Distribute import *

distadd(env, 'utils/spurious_source_code/regexps/assert_0/SConscript')
distadd(env, 'utils/spurious_source_code/regexps/assert_0/allowed')
distadd(env, 'utils/spurious_source_code/regexps/assert_0/documentation')
distadd(env, 'utils/spurious_source_code/regexps/assert_0/forbidden')
distadd(env, 'utils/spurious_source_code/regexps/assert_0/regexps')
