Import('*')

from Distribute import distadd, instadd

#will be executed from base dir!
buildcat=PhonyTarget("buildcat", 'cd locale ; ../utils/buildcat.py ; cd -')

instadd(env, 'locale/??_??', 'locale')

distadd(env, 'locale/SConscript')
distadd(env, 'locale/*.po*')

Return('buildcat')

