name: build - macos
on:
  workflow_call:

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release]
        compiler: [clang]
        os: [15, 26, 26-intel]
        # Check https://github.com/actions/runner-images#available-images
        include:
          - os: 26-intel
            osname: macOS26_x86
          - os: 15
            osname: macOS15_arm64
          - os: 26
            osname: macOS26_arm64
    name: ${{ matrix.osname}} ${{ matrix.config }} 
    # ${{ matrix.compiler }}
    runs-on: macos-${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)"
        # Suppress warnings about installing formulas instead of casks. Casks would raise another
        # warning about disabling macos gatekeeper.
        # brew tap-new $USER/local-sdl2
        # brew tap homebrew/core --force
        # brew extract --version=2.32.10 sdl2 $USER/local-sdl2
        # brew extract --version=2.8.10 sdl2_image $USER/local-sdl2
        # brew extract --version=2.8.1 sdl2_mixer $USER/local-sdl2
        # brew extract --version=2.22.0 sdl2_ttf $USER/local-sdl2
        # brew deps --tree $USER/local-sdl2/sdl2_image@2.8.10
        # brew deps --tree $USER/local-sdl2/sdl2_mixer@2.8.1
        # brew deps --tree $USER/local-sdl2/sdl2_ttf@2.22.0
        # brew install $USER/local-sdl2/sdl2@2.32.10
        # brew install $USER/local-sdl2/sdl2_image@2.8.10
        # brew install $USER/local-sdl2/sdl2_mixer@2.8.1
        # brew install $USER/local-sdl2/sdl2_ttf@2.22.0
        ./install-dependencies.sh homebrew --formula
        # temporary fix for macos-14 arm failures
        brew install --quiet icu4c
        brew tap-new $USER/local-sdl2
        brew tap homebrew/core --force
        brew extract --version=2.32.10 sdl2 $USER/local-sdl2
        brew install $USER/local-sdl2/sdl2@2.32.10
        brew list --versions sdl2
        brew unlink sdl2
        brew link --overwrite sdl2@2.32.10
    - name: Building
      env:
        # Exports for build_app.sh
        MATRIX_OS: ${{ matrix.os }}
        TYPE: ${{ matrix.config }}
        COMPILER: ${{ matrix.compiler }}
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh "--${{ matrix.config }}" "--${{ matrix.compiler }}" "--no-website"
        grep -v REVDETECT-BROKEN ../build/VERSION
        DMGPATH="$(pwd)"
        DMGFILE="$(ls *.dmg)"
        echo "DMG file is: $DMGPATH/$DMGFILE"
        mv "$DMGFILE" "${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.osname }}-${{ matrix.config }}-${{ matrix.compiler }}.dmg"

    - name: Uploading DMG
      uses: actions/upload-artifact@v7
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} ${{ matrix.osname }} AppImage
        path: "${{ github.workspace }}/Widelands-${{ github.sha }}-${{ matrix.osname }}-${{ matrix.config }}-${{ matrix.compiler }}.dmg"
