name: MacOS

#on: [push]
on:
  workflow_run:
    workflows: ["Clang-Tidy"]

jobs:
  macos:
    if: ${{ github.event_name }} == 'pull_request'
    env:
      release: notset
      debug: notset
    strategy:
      matrix:
        config:
          - release
          #- debug
        compiler:
          - clang
    name: MacOs ${{ matrix.config }} ${{ matrix.compiler }} Build
    runs-on: macOS-latest
    steps:
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)" && \
        export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH";
        set -ex
        echo "**********************************************"
        echo "Event name ${{ github.event_name }}"
        echo "Event ${{ github.event }}"
        brew install boost ccache doxygen glew ninja sdl2 sdl2_image sdl2_mixer sdl2_ttf
        echo "**********************************************"
        echo "Event name ${{ github.event_name }}"
        echo "Event ${{ github.event }}"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Building
      run: |
        echo "**********************************************"
        echo "Event name ${{ github.event_name }}"
        echo "Event ${{ github.event }}"
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh ${{ matrix.compiler }} ${{ matrix.config }} ../
        ls *.dmg > DMGFILE
        echo "DMG file is: $DMGFILE"
        echo "::set-env name=DMG_${{ matrix.config }}::$DMGFILE"
    #- name: Uploading DMG
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} AppImage
    #    path: ${{ github.workspace }}/build_wl/${{ env.config }}
