name: MacOS

on: [push]

jobs:
  macos:
    strategy:
      matrix:
        config:
          - release
          - debug
        compiler:
          - gcc
    name: MacOs ${{ matrix.config }} ${{ matrix.compiler }} Build
    runs-on: macOS-latest
    steps:
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)" && \
        export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH";
        brew install gcc@7
        brew install boost ccache doxygen glew graphviz ninja sdl2 sdl2_image sdl2_mixer sdl2_ttf
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh ${{ matrix.compiler }} ${{ matrix.config }} ../
