name: MacOS

on: [push]

# macos-latest or macos-10.15

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)" && \
        export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH";
        brew install boost doxygen gcc glew graphviz ninja sdl2 sdl2_image sdl2_mixer sdl2_ttf
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Compile
      run: |
        mkdir build_wl
        cp widelands/utils/macos/build_app.sh build_wl/
        cd build_wl/
        ./build_app.sh gcc release ../widelands/
