name: MacOS

on: [push]

jobs:
  macos:
    if: github.ref != 'refs/heads/master'
    strategy:
      matrix:
        config:
          - release
          #- debug
        compiler:
          - clang
    name: MacOs ${{ matrix.config }} ${{ matrix.compiler }}
    runs-on: macOS-latest
    steps:
    - name: Installing dependencies
      run: |
        export ICU_ROOT="$(brew --prefix icu4c)" && \
        export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH";
        brew install boost ccache glew ninja sdl2 sdl2_image sdl2_mixer sdl2_ttf
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Building
      run: |
        mkdir build_wl
        cd build_wl/
        ../utils/macos/build_app.sh ${{ matrix.compiler }} ${{ matrix.config }} ../
        DMGFILE="$(ls *.dmg)"
        echo "DMG file is: $DMGFILE"
        echo "::set-env name=dmg::${{ github.workspace }}/build_wl/$DMGFILE"
        echo "Environment variable: ${{ env.dmg }}"

    - name: Uploading DMG
      uses: actions/upload-artifact@v2
      with:
        name: Widelands ${{ matrix.config }} ${{ matrix.compiler }} AppImage
        path: ${{ env.dmg }}
        # path: ${{ github.workspace }}/build_wl/${{ env.dmg }}
        # /Users/runner/work/widelands/widelands/build_wl/widelands_10.9_1.0~git1[1d5301b@build-macos].dmg
