#! /bin/bash

declare -i RESULT=0
for TEST in *; do
	if [ -d $TEST ]; then
		[[ -f $TEST/forbidden ]] && if [ "$(egrep -f $TEST/regexps $TEST/forbidden | wc -l)" != "$(wc -l < $TEST/forbidden)" ]; then
			echo "$TEST failed to match all forbidden cases"
			RESULT+=1
		fi
		[[ -f $TEST/forbidden ]] && if [ "$(egrep -f $TEST/regexps $TEST/allowed | wc -l)" != "0" ]; then
			echo "$TEST detected an allowed case as forbidden"
			RESULT+=1
		fi
	fi
done
if [ $RESULT == 0 ]; then
	echo "All regexps passed their tests"
else
	echo "$RESULT errors were found during the regexp tests"
fi
exit $RESULT
